#!/bin/bash

WALL_DIR="/home/shadowg_2004/Pictures/Wallhaven/Spaceout/"

WALLPAPERS=("$WALL_DIR"/*)

RAN_WALL="${WALLPAPERS[RANDOM % ${#WALLPAPERS[@]}]}"

xwallpaper --zoom "$RAN_WALL"

wal -i "$RAN_WALL"
